site_name: frameserver
site_description: The ultimate picture frame REST server
repo_url: https://github.com/mxdmedia/frame-server
site_dir: site
copyright: Copyright &copy; 2015, <a href="https://github.com/mxdmedia">mxdmedia</a>.

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
