# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationkeys', '0002_remove_registrationkey_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationkey',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
